--- 
- 
  become: true
  hosts: webservers
  name: "Config Web VM with Docker"
  tasks: 
    - 
      apt: 
        name: docker.io
        state: present
        update_cache: true
      name: docker.io
    - 
      apt: 
        name: python3-pip
        state: present
      name: "Install pip3"
    - 
      name: "Install Docker python module"
      pip: 
        name: docker
        state: present
    - 
      docker_container: 
        image: cyberxsecurity/dvwa
        name: dvwa
        published_ports: "80:80"
        restart_policy: always
        state: started
      name: "download and launch a docker web container"
    - 
      name: "Enable docker service"
      systemd: 
        enabled: true
        name: docker

