---
 -
  become: true
  hosts: webservers
  name: "Config Web VM with Docker"
  tasks:
    -
      apt:
        force_apt_get: true
        name: docker.io
        state: present
      name: docker.io
    -
      apt:
        force_apt_get: true
        name: python-pip
        state: present
      name: "Install pip"
    -
      name: "Install Docker python module"
      pip:
        name: docker
        state: present
    -
      docker_container:
        image: cyberxsecurity/dvwa
        name: dvwa
        published_ports: "80:80"
        state: started
      name: "download and launch a docker web container"
    -
      name: "Enable docker service"
      systemd:
        enabled: true
        name: docker
